language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - nightly
arch:
  - amd64

jobs:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: 8.1
    - php: 8.2
    - php: 8.3
    - php: nightly
  include:
    - php: 5.4
      dist: precise
      arch: amd64
    - php: 5.5
      dist: trusty
      arch: amd64

install:
  - pear install package.xml
  - |
      if [[ $TRAVIS_PHP_VERSION = 5.4 ]]; then
        echo "Skipping composer install check."
      else
        composer install
      fi
script:
  - phpunit tests
